config/routes.rb
Rails.application.routes.draw do
   
  root 'menus#index'

  #メニュー
  get    'menus/show/:id',   to: 'menus#show',    as: 'menu_show'
  get    'menus/new',        to: 'menus#new',     as: 'menu_new'
  post   'menus/create',     to: 'menus#create',  as: 'menu_create'
  get    'menus/edit/:id',   to: 'menus#edit',    as: 'menu_edit'
  patch  'menus/update/:id', to: 'menus#update',  as: 'menu_update'
  delete 'menus/delete/:id', to: 'menus#destroy', as: 'menu_delete'

  #材料
  get    'ingredient/index',      to: 'ingredients#index',   as: 'ing_index'
  get    'ingredient/new',        to: 'ingredients#new',     as: 'ing_new'
  post   'ingredient/create',     to: 'ingredients#create',  as: 'ing_create'
  get    'ingredient/edit/:id',   to: 'ingredients#edit',    as: 'ing_edit'
  patch  'ingredient/update/:id', to: 'ingredients#update',  as: 'ing_update'
  delete 'ingredient/delete/:id', to: 'ingredients#destroy', as: 'ing_delete'

  #ユーザー
  get    'users/new',        to: 'users#new',    as:  'user_new'
  post   'users/create',     to: 'users#create', as:  'user_create'
  get    'users/edit/:id',   to: 'users#edit',   as:  'user_edit'
  patch  'users/update/:id', to: 'users#update', as:  'user_update'
  delete 'users/delete/:id', to: 'users#destroy', as: 'user_delete'
  
  #ログイン/ログアウト
  get    'login',           to: 'sessions#new',         as: 'login'
  post   'sessions/create', to: 'sessions#create',      as: 'login_create'
  delete 'logout',          to: 'sessions#destroy',     as: 'logout'
  get    'admin_login',     to: 'sessions#admin_login', as: 'admin_login'

  #カート保存/削除
  get    'carts/list',      to: 'carts#index',   as: 'cart_list'
  post   'index/carts/in2', to: 'carts#create',  as: 'index_cart_in'
  patch  'carts/in',        to: 'carts#update',  as: 'cart_in'
  delete 'carts/out',       to: 'carts#destroy', as: 'cart_out'

  #注文
  get  'orders/index',  to: 'orders#index',  as: 'order'
  get  'orders/new',    to: 'orders#new',    as: 'order_new'
  post 'orders/check',  to: 'orders#check',  as: 'order_check'
  post 'orders/create', to: 'orders#create', as: 'order_create'
  get  'orders/fin',    to: 'orders#fin',    as: 'order_fin'
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :carts
    has_many :products
    has_many :purchasehistries

    #has_one_attached :image
    mount_uploader :image, ImageUploader

    validates :name, presence: true
    validates :price, presence: true
    validates_length_of :description, maximum: 300
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.where(del_flg: false).order(:id)
    if session[:user_id] == 1
      @admin_user = true
    else
      @admin_user = false
    end
    menu_in_top3 = []
    @nocount = 1
    count = 0
    top3 = PurchaseHistrie.where(created_at: Time.current.prev_month..Time.current).group(:menu_id).order('count_all DESC').count
    top3.each do |menu_id, sum_count|
      if count == 3
        break
      else
        del_menu = Menu.find(menu_id)
        if  del_menu.del_flg == true
        else
          menu_in_top3.push(Menu.find(menu_id))
          count += 1
        end
        
      end
    end
    @no1 = menu_in_top3[0]
    @no2 = menu_in_top3[1]
    @no3 = menu_in_top3[2]

  end

  def show
    @menu = current_menu
    @products = get_product

    #アレルギー名称 材料名称 取得
    @allergy = []
    @ing_name = []
    @products.each do |product|
      if product.ingredient.allergy_name == "無し"
        @ing_name.push(product.ingredient.name)
      else
        @allergy.push(product.ingredient.allergy_name)
        @ing_name.push(product.ingredient.name)
      end
    end
    if @allergy.blank?
      @allergy.push("ありません")
    end
  end

  def new
    @menu = Menu.new
    @ingredients = ing_all.order(:id)
  end

  def create
    @menu = Menu.new(menu_params)
    @ingredients = ing_all
    ActiveRecord::Base.transaction do
      if params[:menu][:image].present?
        if params[:menu][:ingredient].present?
          if @menu.save!
            @menuid = Menu.find_by(name: params[:menu][:name])
            params[:menu][:ingredient].each do |ingredient|
              #追加したメニューと材料情報をproductテーブルに格納
              product = Product.new
              product.ingredient_id = ingredient
              product.menu_id = @menuid.id
              product.save!
            end
            flash[:notice] = "新規メニューを登録しました"
            redirect_to root_path
          else
            render :new 
          end
        else
          flash.now[:alert] = "使用している材料を1つ以上選択してください"
          render :new
        end
      else
        flash.now[:alert] = "画像を登録してください"
        render :new
      end
    end
    rescue => e
    flash[:alert] =  "メニューの登録に失敗しました。登録内容を確認し、再度処理を実施してください。"
    redirect_to menu_new_path
  end

  def edit
    @menu = current_menu
    @ingredients = ing_all.order(:id)
    @products = get_product

    #材料名称 取得
    @ing_name = []
      @products.each do |product|
        @ing_name.push(product.ingredient.name)
      end
  end

  def update
    @menu = current_menu
    @ingredients = ing_all
    @products = get_product

     #材料名称 取得
     @ing_name = []
     @products.each do |product|
       @ing_name.push(product.ingredient.name)
     end
    
    ActiveRecord::Base.transaction do
      #材料が選択されているか確認
      if params[:menu][:ingredient].blank?
      else
        #編集中メニューのproductテーブルの紐付けを一度解除(del_flg⇒true)
        product_menu = Product.where(menu_id: params[:id])
        product_menu.each do |pmenu|
          if pmenu.update!(del_flg: true)
          end
        end
        #編集で選択された材料毎にproductテーブルの作成/紐付け(def_flg⇒false)
        params[:menu][:ingredient].each do |ing_id| 
          create_product = Product.where(menu_id: params[:id], ingredient_id: ing_id)
          if create_product.blank?
            if Product.create!({ menu_id: params[:id], ingredient_id: ing_id, del_flg: false })
            end
          else
            if create_product.update(del_flg: false)
            end
          end
        end
      end

      if params[:menu][:ingredient].blank?
          flash[:alert] = "使用している材料を選択してください"
          redirect_to menu_edit_path
      else
          if @menu.update!(menu_params)
            flash[:notice] = "メニュー情報を更新しました。"
            redirect_to menu_edit_path 
          else
            render :edit
          end
      end
    end 
    rescue => e
      flash[:alert] =  "メニューの更新に失敗しました。登録内容を確認し、再度処理を実施してください。"
      redirect_to menu_edit_path 
  end

  def destroy
    @menu = current_menu
    if @menu.update(del_flg: true)
      flash[:notice] = "削除しました"
      redirect_to root_path
    else
      flash.now[:alert] = "メニューの削除に失敗しました。もう一度処理を実施してください"
      render :index
    end
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :price, :image, :description)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
    def current_menu
        return Menu.find_by(id: params[:id])
    end
end

app/views/menus/edit.html.erb
<main>
  <div class="menu_edit">
    <h1>商品編集</h1>
    <%= form_with model: @menu, url: menu_update_path,  local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <label>材料名</label><br>
      <%= f.text_field :name %><br>
      <label>価格</label><br>
      <%= f.number_field :price %><br>
      <label>画像</label><br>
      <%= f.file_field :image %><br>
      <label>説明文(300文字以内)</label><br>
      <%= f.text_area(:description, size: "50x13") %><br>
      <br>
        ↓使用している材料にチェックを入れる↓<br>
      <!-- 使用している材料のチェックボックス処理 -->
      <% @ingredients.each do |ingredient| %>
      <% show_flg = false %>
        <% @ing_name.each do |ing_name| %>
            <% if ingredient.name == ing_name %>
                <label><%= ingredient.name %></label>
                <input type="checkbox" name="menu[ingredient][]" value="<%= ingredient.id %>" checked = {true} /><br>
                <% show_flg = true %>
                <% break %>
            <% end %>
        <% end %>
        <% if show_flg == false %>  
            <label><%= ingredient.name %></label>
            <input type="checkbox" name="menu[ingredient][]" value="<%= ingredient.id %>"/><br>
        <% end %>
      <% end %>
      <!-- 使用している材料のチェックボックス処理 -->
      <%= f.submit "商品更新" %>
    <% end %>
    <br>
    <%= link_to "一覧に戻る", root_path %>
  </div>
</main>

app/views/menus/index.html.erb
<main>
    <section class="top3">
        <h2><span class="h2">人気のお弁当BEST3</span></h2>
            <div class="menu_top3">
                <% if @no3.nil? %>
                <% else %>
                    <div class="menu_no1">
                        <span class="top3_character">人気No1<i class="fa-solid fa-crown"></i></span><br>
                        <%= link_to image_tag(@no1.image.url), menu_show_path(@no1.id), alt: "お弁当の画像" %><br>
                        <div class="menu_no1_link">
                            <%= link_to @no1.name, menu_show_path(@no1.id) %><br>
                        </div>
                    </div>
                    <div class="menu_no2">
                        <span class="top3_character">人気No2</span><br>
                        <%= link_to image_tag(@no2.image.url), menu_show_path(@no2.id), alt: "お弁当の画像" %><br>
                        <div class="menu_no2_link">
                            <%= link_to @no2.name, menu_show_path(@no2.id) %><br>
                        </div>
                    </div>
                    <div class="menu_no3">
                        <span class="top3_character">人気No3</span><br>
                        <%= link_to image_tag(@no3.image.url), menu_show_path(@no3.id), alt: "お弁当の画像" %><br>
                        <div class="menu_no3_link">
                            <%= link_to @no3.name, menu_show_path(@no3.id) %><br>
                        </div>
                    </div>
                <% end %>

                
            </div>
    </section>
    <br>
    <section class="menus">
    <h1>商品一覧<hr></h1>
    <% if @admin_user == true %>
        <%= link_to "新規商品追加", menu_new_path %>/<%= link_to "材料一覧", ing_index_path %><br>
    <% end %>
        <div class="menu_list">
            <% @menus.each do |menu| %>
            <div class="menu_list_content">
                <%= link_to image_tag(menu.image.url), menu_show_path(menu.id), alt: "お弁当の画像" %><br>
                <hr>
                <div class="menu_links">
                    <%= link_to menu.name, menu_show_path(menu.id) %> 
                    <% if @admin_user == true %>
                        <%= link_to "編集", menu_edit_path(menu.id) %>&nbsp;
                        <%= link_to "削除", menu_delete_path(menu.id), method: :delete, 
                                    data: { confirm: "本当に削除して良いですか?", cancel: "やめる", commit: "削除する"}, title: "削除確認" %> <br>
                    <% end %>
                </div>
                <%= menu.price %>円<br>
                <br>
                <%= form_with model: @menus, url: index_cart_in_path do |f| %>
                    <%= f.hidden_field :menu_id, value: menu.id %>
                    <label>個数</label><%= f.number_field :quantity, in: 1.0..20.0, step: 1, value: 1 %><br>
                    <%= f.submit "カートに追加する" %>
                <% end %>
                <br>
            </div>
            <% end %>
        </div>
    </section>
</main>

app/views/menus/new.html.erb
<main>
  <div class="new_menu">
    <%= form_with model: @menu, url: menu_create_path, local: true do |f| %>
      <h1>新規商品登録</h1>
      <label>材料名</label><br>
      <%= f.text_field :name %><br>
      <label>価格</label><br>
      <%= f.number_field :price %><br>
      <label>画像</label><br>
      <%= f.file_field :image %><br>
      <label>説明文(300文字以内)</label><br>
      <%= f.text_area(:description, size: "50x13") %><br>
      <br>
      使用している材料にチェックを入れる<br>
      <% @ingredients.each do |ingredient| %>
      <label><%= ingredient.name %></label>
      <input type="checkbox" name="menu[ingredient][]" value="<%= ingredient.id %>" /><br>
      <% end %>
      <br>
      <span class="menu_create_Notes">※全ての内容を入力してから商品登録を実施してください</span><br>
      <%= f.submit "商品登録" %> 
    <% end %>
  </div>
</main>

app/views/menus/show.html.erb
<main>
  <div class="menu_detail">
    <h1>商品詳細</h1>
      <span class="menu_name"><%= @menu.name %><br></span> 
      <div class="allergy_info"><i class="fa-solid fa-circle-exclamation"></i>使用しているアレルギー
        <% @allergy.each do |allergy|%>
          <%= allergy %>
        <% end %>
      </div>
      <div class="image_description">
        <%= image_tag @menu.image.url, alt: "お弁当の画像" %><br>
        <span class="menu_description"><%= @menu.description %></span>
      </div><br>
      <label>価格:</label><%= @menu.price %>円<br>
    <br>
    <%= form_with model: @menu, url: cart_in_path do |f| %>
      <%= f.hidden_field :menu_id, value: @menu.id %>
      <label>個数</label><%= f.number_field :quantity, in: 1.0..20.0, step: 1, value: 1 %><br>
      <%= f.submit "カートに追加する" %>
    <% end %>
    <br>
    <div class="use_ing_list">
      使用している材料<br>
      <% @ing_name.each do |ing_name| %>
        ・<%= ing_name%>
      <% end%>
    </div>
    <br>
    <br>
    <%= link_to "一覧に戻る", root_path %>
  </div>
</main>