config/routes.rb
Rails.application.routes.draw do
   
  root 'menus#index'

  #メニュー
  get    'menus/show/:id',   to: 'menus#show',    as: 'menu_show'
  get    'menus/new',        to: 'menus#new',     as: 'menu_new'
  post   'menus/create',     to: 'menus#create',  as: 'menu_create'
  get    'menus/edit/:id',   to: 'menus#edit',    as: 'menu_edit'
  patch  'menus/update/:id', to: 'menus#update',  as: 'menu_update'
  delete 'menus/delete/:id', to: 'menus#destroy', as: 'menu_delete'

  #材料
  get    'ingredient/index',      to: 'ingredients#index',   as: 'ing_index'
  get    'ingredient/new',        to: 'ingredients#new',     as: 'ing_new'
  post   'ingredient/create',     to: 'ingredients#create',  as: 'ing_create'
  get    'ingredient/edit/:id',   to: 'ingredients#edit',    as: 'ing_edit'
  patch  'ingredient/update/:id', to: 'ingredients#update',  as: 'ing_update'
  delete 'ingredient/delete/:id', to: 'ingredients#destroy', as: 'ing_delete'

  #ユーザー
  get    'users/new',        to: 'users#new',    as:  'user_new'
  post   'users/create',     to: 'users#create', as:  'user_create'
  get    'users/edit/:id',   to: 'users#edit',   as:  'user_edit'
  patch  'users/update/:id', to: 'users#update', as:  'user_update'
  delete 'users/delete/:id', to: 'users#destroy', as: 'user_delete'
  
  #ログイン/ログアウト
  get    'login',           to: 'sessions#new',         as: 'login'
  post   'sessions/create', to: 'sessions#create',      as: 'login_create'
  delete 'logout',          to: 'sessions#destroy',     as: 'logout'
  get    'admin_login',     to: 'sessions#admin_login', as: 'admin_login'

  #カート保存/削除
  get    'carts/list',      to: 'carts#index',   as: 'cart_list'
  post   'index/carts/in2', to: 'carts#create',  as: 'index_cart_in'
  patch  'carts/in',        to: 'carts#update',  as: 'cart_in'
  delete 'carts/out',       to: 'carts#destroy', as: 'cart_out'

  #注文
  get  'orders/index',  to: 'orders#index',  as: 'order'
  get  'orders/new',    to: 'orders#new',    as: 'order_new'
  post 'orders/check',  to: 'orders#check',  as: 'order_check'
  post 'orders/create', to: 'orders#create', as: 'order_create'
  get  'orders/fin',    to: 'orders#fin',    as: 'order_fin'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :products

    validates :name, presence: true
    validates :allergy_name, presence: true

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = ing_all.order(:id)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ing_params)
    if @ingredient.save
      flash[:notice] =  "新規材料を登録しました。"
      redirect_to ing_index_path
    else
      render :new
    end
  end

  def edit
    @ingredient = current_ing
  end

  def update
    @ingredient = current_ing
    if @ingredient.update(ing_params)
      flash[:notice] =  "材料情報を更新しました。"
      redirect_to ing_index_path
    else
      render :edit
    end
  end

  def destroy
    ingredient = current_ing
    ActiveRecord::Base.transaction do
      #productテーブルで削除した材料が紐付けられていたら削除する
      product_list = Product.where(ingredient_id: params[:id])
      product_list.each do |product|
        product.update!(del_flg: true)
      end

      #削除した材料をingテーブルで削除する
      if ingredient.update!(del_flg: true)
        flash[:notice] =  "削除しました。"
        redirect_to ing_index_path
      else
        render :index
      end
    end
    rescue => e
    flash[:alert] =  "削除に失敗しました。再度処理を実施してください。"
    redirect_to ing_index_path
  end
  

  private
  def ing_params
    params.require(:ingredient).permit(:name,:allergy_name)
  end
  
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

        #削除されていない全ての材料情報を取得
        def ing_all
            Ingredient.where(del_flg: false)
        end
        
        #商品と材料の紐づけが有効なものを取得  
        def get_product
          Product.where(del_flg: false).where(menu_id: params[:id]).order(ingredient_id: :DESC)
        end

        def current_ing
          Ingredient.find(params[:id])
        end
end

app/views/ingredients/edit.html.erb
<main>
  <div class="ing_update">
    <h1>材料情報更新</h1>
    <%= form_with model: @ingredient, url: ing_update_path, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      材料名:<%= f.text_field :name %>
      アレルギー名<%= f.select :allergy_name, [["卵", "卵"], ["乳", "乳"],["小麦","小麦"],["えび","えび"],["かに","かに"],["落花生","落花生"],["そば","そば"],["無し","無し"]], include_blank: "選択して下さい" %>
      <%= f.submit "材料更新" %>
    <% end %>
  </div>
</main>

app/views/ingredients/index.html.erb
<main>
  <div class="ing_list">
    <h1>材料一覧</h1>
    <%= link_to "新規材料登録", ing_new_path %><br>
    <br> 
    <label class="list_title">材料名/アレルギー</label><br>
      <% @ingredients.each do |ingredient| %>
        <%= ingredient.name %>/<%= ingredient.allergy_name %>
        ( <%= link_to "編集", ing_edit_path(ingredient.id) %> 
        <%= link_to "削除", ing_delete_path(ingredient.id), method: :delete, 
        data: { confirm: "本当に削除して良いですか?", cancel: "やめる", commit: "削除する"}, title: "削除確認" %> )<br>
        -------------------------------<br>
      <% end %>
  </div>
</main>

app/views/ingredients/new.html.erb
<main>
  <div class="ing_create">
    <h1>新規材料登録</h1>
    <%= form_with model: @ingredient, url: ing_create_path, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      材料名<br>
      <%= f.text_field :name %><br>
      アレルギー名<br>
      <%= f.select :allergy_name,
      [["卵", "卵"], ["乳", "乳"],["小麦","小麦"],["えび","えび"],["かに","かに"],["落花生","落花生"],["そば","そば"],["無し","無し"]],
      include_blank: "選択して下さい" %><br>
      <br>
      <span class="menu_create_Notes">※全ての内容を入力してから材料登録を実施してください</span><br>
      <%= f.submit "材料登録" %><br>
      <br>
    <% end %>
    <%= link_to "材料一覧に戻る", ing_index_path %>
  </div>
</main>