config/routes.rb
Rails.application.routes.draw do
   
  root 'menus#index'

  #メニュー
  get    'menus/show/:id',   to: 'menus#show',    as: 'menu_show'
  get    'menus/new',        to: 'menus#new',     as: 'menu_new'
  post   'menus/create',     to: 'menus#create',  as: 'menu_create'
  get    'menus/edit/:id',   to: 'menus#edit',    as: 'menu_edit'
  patch  'menus/update/:id', to: 'menus#update',  as: 'menu_update'
  delete 'menus/delete/:id', to: 'menus#destroy', as: 'menu_delete'

  #材料
  get    'ingredient/index',      to: 'ingredients#index',   as: 'ing_index'
  get    'ingredient/new',        to: 'ingredients#new',     as: 'ing_new'
  post   'ingredient/create',     to: 'ingredients#create',  as: 'ing_create'
  get    'ingredient/edit/:id',   to: 'ingredients#edit',    as: 'ing_edit'
  patch  'ingredient/update/:id', to: 'ingredients#update',  as: 'ing_update'
  delete 'ingredient/delete/:id', to: 'ingredients#destroy', as: 'ing_delete'

  #ユーザー
  get    'users/new',        to: 'users#new',    as:  'user_new'
  post   'users/create',     to: 'users#create', as:  'user_create'
  get    'users/edit/:id',   to: 'users#edit',   as:  'user_edit'
  patch  'users/update/:id', to: 'users#update', as:  'user_update'
  delete 'users/delete/:id', to: 'users#destroy', as: 'user_delete'
  
  #ログイン/ログアウト
  get    'login',           to: 'sessions#new',         as: 'login'
  post   'sessions/create', to: 'sessions#create',      as: 'login_create'
  delete 'logout',          to: 'sessions#destroy',     as: 'logout'
  get    'admin_login',     to: 'sessions#admin_login', as: 'admin_login'

  #カート保存/削除
  get    'carts/list',      to: 'carts#index',   as: 'cart_list'
  post   'index/carts/in2', to: 'carts#create',  as: 'index_cart_in'
  patch  'carts/in',        to: 'carts#update',  as: 'cart_in'
  delete 'carts/out',       to: 'carts#destroy', as: 'cart_out'

  #注文
  get  'orders/index',  to: 'orders#index',  as: 'order'
  get  'orders/new',    to: 'orders#new',    as: 'order_new'
  post 'orders/check',  to: 'orders#check',  as: 'order_check'
  post 'orders/create', to: 'orders#create', as: 'order_create'
  get  'orders/fin',    to: 'orders#fin',    as: 'order_fin'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
   cart_list
   cart_list_price
  end

  def check
    cart_list
    cart_list_price
    @user.address = params[:address]

    @check = Check.new(email: params[:email])
    if @check.valid?
    else
      flash.now[:alert] = "メールアドレスが正しく入力されていません"
      render :new
    end
  
    #配達希望の場合の送料を追加
    if params[:receive] == "delivery"
      @total_price += 300
    end

      case params[:receive]
      when "shop"
        session[:receive] = "店舗で受け取る"
      when "delivery"
        session[:receive] = "自宅まで配達を希望　料金+300円"
      else
        session[:receive] = "お弁当の受け取り方法が選択されていません"
      end
   
    session[:email] = params[:email]
    session[:tel] = params[:tel]
    session[:post_code] = params[:post_code]
    session[:address] = params[:address]
  end

  def create
   cart_list
   cart_list_price
   if session[:receive] == "自宅まで配達を希望　料金+300円"
    @total_price += 300
   end

   ActiveRecord::Base.transaction do 
    #今回の注文番号の作成
    ordernumber = OrderNumber.find(1)
    @number = ordernumber.number += 1
    if ordernumber.update!(number: @number)
    else
    end
     #注文確定したメニューをPurchaseHistrieにレコードを追加する
     @cart.each do |cart|
       if PurchaseHistrie.create!(menu_id: cart.menu_id, user_id: @user.id)
       else
       end
     end
     #カートに追加していたメニューのdel_flgをtrueに変更する
     @cart.each do |cart|
       if cart.update!(del_flg: true)
       end
     end
   rescue => e
    flash.now[:alert] =  "注文確定処理でエラーが発生しました。注文が完了していないため、お手数ですが店舗までご連絡をお願いいたします。"
    render :check
   end
    #お弁当の受け取り方法によって送信するメールを判別
    case session[:receive] 
    when "店舗で受け取る"
      if OrderMailMailer.order_mail(session[:email],@cart,@user,session[:receive],session[:tel],@total_price,@number).deliver
        redirect_to order_fin_path
      else
        flash.now[:alert] = "注文確定処理でエラーが発生しました。注文が完了していないため、お手数ですが店舗までご連絡をお願いいたします。"
        redirect_to root_path
      end
    when "自宅まで配達を希望　料金+300円"
      if DeliveryMailMailer.delivery_mail(session[:email],@cart,@user,session[:receive],session[:post_code],session[:address],session[:tel],@total_price,@number).deliver
        redirect_to order_fin_path
        else
        flash.now[:alert] = "注文確定処理でエラーが発生しました。注文が完了していないため、お手数ですが店舗までご連絡をお願いいたします。"
        redirect_to root_path
      end
    end
    session[:email] = nil
    session[:tel] = nil
    session[:post_code] = nil
    session[:address] = nil
    session[:receive] = nil
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
    def cart_list
        if session[:user_id].nil?
            @cart = Cart.where(id_number: session[:guest_id]).where(del_flg: false)
            @user = User.find(2)
            if params[:email].present?
                @user.email = params[:email]
                @user.tel = params[:tel]
            else
                @user.email = nil
                @user.tel = nil
            end
        else
            @cart = Cart.where(id_number: session[:user_id]).where(del_flg: false)
            @user = User.find(session[:user_id])
            if params[:email].present?
                @user.email = params[:email]
                @user.tel = params[:tel]
            end
         end
    end
    #メニュー合計
    def cart_list_price
        @total_price = 0
        @cart.each do |cart|
            @total_price += cart.menu.price
        end
    end
end

app/views/orders/check.html.erb
<main>
  <div class="order_confirm">
      <h3>以下の内容でご注文を承ります</h3>
      <br>
      <h1>注文商品一覧</h1>
      <div class="check_menu">
        <% @cart.each do |cart| %>
          <%= form_with model: @cart, url: cart_out_path, method: :delete do |f| %>
            <%= cart.menu.name %> 
            <%= cart.menu.price %>円
            <%= f.hidden_field :cart_id, value: cart.id %>
          <% end %>  
        <% end %> 
      </div>
      <br>
      <label>合計<%= @total_price %>円</label><br>
      <br>
      <%= form_with url: order_create_path  do |f| %>
        <%= f.label "■お弁当の受け取り方法" %><br>
        <%= f.label " ・#{session[:receive]}" %><br>
        <br>
        <%= f.label "■メールアドレス" %><br>
        <%= f.label session[:email] %><br>
        <%= f.label "■電話番号" %><br>
        <%= f.label session[:tel] %><br>
        <%= f.label "■郵便番号" %><br>
        <%= f.label session[:post_code] %><br>
        <%= f.label "■お届け先" %><br>
        <%= f.label session[:address] %><br>
        <%= f.label "合計" %><br>
        <%= f.label @total_price %>円<br>
        <br>
        <%= f.submit "注文確定" %>
      <% end %>
    </div>
</main>

app/views/orders/fin.html.erb
<main>
    <div class="order_fin">
        <h1>ご注文ありがとうございました。</h1><br>
        入力いただいたメールアドレス宛にメールを送信いたしました。<br>
        メールが届くまで少々お待ちください。<br>
        しばらくお待ちいただいても、メールが届かない場合は、<br>
        大変お手数ですが、店舗までご連絡をお願いいたします。<br>
    </div>
</main>

app/views/orders/new.html.erb
<main>
  <div class="order_new">
    <h1>注文商品一覧</h1>
    <div class="order_menu">
      <% @cart.each do |cart| %>
        <%= form_with model: @cart, url: cart_out_path, method: :delete do |f| %>
          <%= cart.menu.name %> 
          <%= cart.menu.price %>円
          <%= f.hidden_field :cart_id, value: cart.id %>
        <% end %>  
      <% end %>
    </div> 
    <br>
    <label>小計<%= @total_price %>円</label><br>
    <br>
    <span class="receive">お弁当の受け取り方法</span><br>
    <%= form_with url: order_check_path, local: true  do |f| %>
        <%= f.radio_button :receive, :shop, checked: true, id: :shop_btn %>
        <%= f.label :receive, "店舗で受け取る" %><br>
        <%= f.radio_button :receive, :delivery, id: :delivery_btn %>
        <%= f.label :receive, "自宅まで配達を希望　料金+300円" %><br>
        <%= f.label "メールアドレス" %><span class="required">※</span><br>
        <%= f.text_field :email, value: @user.email, required: true, class: "order_mail" %><br>
        <%= f.label "電話番号(ハイフン不要)" %><span class="required">※</span><br>
        <%= f.number_field :tel, value: @user.tel, required: true  %><br>
        <span class="required">※</span>は必須入力です<br>
        <br>
        <span class="receive_delivery">※自宅まで配達を希望</span>を選択された場合は、下記についてもご入力ください<br>
        <span class="receive_delivery">※お届け先によっては、配達をお断りする場合がございますことをご了承ください</span><br>
        <%= f.label "郵便番号(ハイフン不要)" %><br>
        <%= f.number_field :post_code, value: @user.post_code, id: :delivery_post_code, class: "order_post_code" %><br>
        <%= f.label "お届け先" %><br>
        <%= f.text_field :address, value: @user.address, id: :delivery_address, class: "order_address" %><br>
        <br>
        <%= f.submit "確認画面へ" %>
        <!-- 自宅まで配達希望時のお届け先入力制御 -->
        <script>
          document.getElementById("delivery_btn").onclick = (function() {
          document.getElementById("delivery_post_code").required = true;
          document.getElementById("delivery_address").required = true;
          });
          document.getElementById("shop_btn").onclick = (function() {
          document.getElementById("delivery_post_code").required = false;
          document.getElementById("delivery_address").required = false;
          });          
        </script>
        <!-- 自宅まで配達希望時のお届け先入力制御 -->
    <% end %>
  </div>
</main>